// قائمة النصوص بجميع اللغات — الصفحة الرئيسية (index.html)
const translations = {
  en: {
    dir: "ltr",

    // Navigation
    home: "Home",
    about: "About",
    focus: "Focus Areas",
    approach: "Approach",
    contact: "Contact",
    portfolio: "Portfolio",

    // Hero (the "ZAYED.ART" wordmark itself is never translated)
    heroSubtitle: "Multidisciplinary Digital Studio",
    ctaBtn: "Start a Project",
    scroll: "Scroll",

    // About
    aboutHeading: "Building Digital<br>Experiences",
    aboutBody1: "Zayed Art is a multidisciplinary digital studio specializing in web development, UI/UX design, mobile applications, and digital marketing solutions.",
    aboutBody2: "We combine creativity with technical expertise to build digital products that drive real business results.",
    techPill1: "WordPress · React · Python",
    techPill2: "Kotlin · Jetpack Compose",
    techPill3: "Adobe Creative Cloud",
    techPill4: "Meta Ads · SEO · Automation",
    domainWebNum: "WEB",
    domainWebLabel: "Development & Platforms",
    domainMobileNum: "MOBILE",
    domainMobileLabel: "Android Applications",
    domainDesignNum: "DESIGN",
    domainDesignLabel: "UI/UX & Branding",
    domainGrowthNum: "GROWTH",
    domainGrowthLabel: "Marketing & Automation",
    statusLabel: "// Current status",
    statusText: "Currently in development phase",
    statusSub: "We're building our first generation of products and services — launching soon.",

    // Focus Areas
    focusHeading: "What We Do",
    webDevTitle: "Web Development",
    webDevSubtitle: "Custom Web & WordPress Solutions",
    webDevDesc: "Tailored web platforms and WordPress solutions engineered for speed, stability, and high performance.",
    webDevFeature1: "Custom WordPress Development",
    webDevFeature2: "Landing Pages & Sales Funnels",
    webDevFeature3: "React & Web Application Interfaces",
    webDevFeature4: "Performance Optimization",

    mobileTitle: "Mobile Applications",
    mobileSubtitle: "Android Apps with Modern Architecture",
    mobileDesc: "Native Android applications built with Kotlin and Jetpack Compose, focused on clean architecture and seamless experiences.",
    mobileFeature1: "Kotlin & Jetpack Compose",
    mobileFeature2: "State Management",
    mobileFeature3: "Material UI Layouts",
    mobileFeature4: "App Publishing Preparation",

    designTitle: "Design & Branding",
    designSubtitle: "Interface Design & Brand Identity",
    designDesc: "User-centered visuals that balance aesthetics with functionality, from brand identities to seamless app and web layouts.",
    designFeature1: "Brand Identity & Logo Design",
    designFeature2: "Mobile & Web UI Design",
    designFeature3: "Figma Prototyping",
    designFeature4: "Premium Visual Assets",

    marketingTitle: "Digital Marketing",
    marketingSubtitle: "Performance Marketing & Automation",
    marketingDesc: "Data-driven strategies that put brands in front of high-value audiences and streamline communication through automation.",
    marketingFeature1: "Meta & Google Ads",
    marketingFeature2: "High-Value Lead Generation",
    marketingFeature3: "Marketing & WhatsApp Automation",
    marketingFeature4: "Local SEO & Visibility",

    // Approach
    approachHeading: "How We Work",
    approach1Title: "Quality First",
    approach1Desc: "Every pixel, every line of code matters. We maintain the highest standards in everything we create.",
    approach2Title: "AI-Powered Workflows",
    approach2Desc: "Integrating advanced AI tools and automation to deliver faster, smarter, and more efficient results.",
    approach3Title: "Performance-Driven",
    approach3Desc: "Built to convert, designed to scale. Every decision is backed by data and focused on results.",

    // Contact & Footer
    contactHeading: "Let's Build<br>Something Great",
    emailLabel: "Email",
    phoneLabel: "Phone",
    copyrightText: "© 2026 Zayed.Art. All rights reserved.",

    // ==== Portfolio page (portfolio.html) ====
    pf3dCardDesc: "Designing 3D environments and assets with adherence to:",
    pf3dCardTitle: "3D Modeling",
    pf3dItem1: "Accurate realistic scales and dimensions",
    pf3dItem2: "Realistic lighting and radiation standards",
    pf3dItem3: "Artistic output and integrated environmental design",
    pfAchievementsHeading: "Marketing Achievements & Asset Acquisition",
    pfAchievementsLabel: "02 — Achievements",
    pfAchievementsNav: "Achiev.",
    pfAiWorkflows: "AI-Assisted Workflows",
    pfAndroidCardDesc: "Active training and mobile app development using Kotlin and Android Studio:",
    pfAndroidCardTitle: "Android App Development",
    pfAndroidItem2: "State Management",
    pfAndroidItem3: "Layout Modifiers",
    pfAppsNote: "<strong>ZaMister:</strong> Student attendance management platform with WhatsApp notifications.<br>\n                <strong>ZaMoney:</strong> Personal budget and expense tracking app.",
    pfAxis1: "Anatomy of professional cameras and their mechanism.",
    pfAxis2: "Studying types of lenses and their practical uses.",
    pfAxis3: "Shooting in Manual Mode professionally.",
    pfAxis4: "Composition rules and various photography techniques and types.",
    pfAxis5: "Basics of lighting and exposure control.",
    pfAxis6: "Image processing and mastering editing using Adobe Lightroom.",
    pfBackHome: "← Back to Home",
    pfBuy: "Buy",
    pfCard1Item1: "Meta Ads Manager (Facebook/Instagram)",
    pfCard1Item2: "TikTok Ads Manager",
    pfCard1Item3: "Campaign Setup & A/B Testing",
    pfCard1Item4: "Audience Targeting & Retargeting",
    pfCard1Title: "Paid Campaign Management",
    pfCard2Item1: "Acquiring high-intent leads",
    pfCard2Item2: "Maintaining real estate portfolio value",
    pfCard2Item3: "Expanding conversion funnel",
    pfCard2Item4: "CRM & Inquiry Processing",
    pfCard2Title: "Lead Generation & Portfolio Growth",
    pfCard3Item1: "ROI/ROAS Optimization",
    pfCard3Item2: "Analytics Tracking",
    pfCard3Item3: "CPL Reduction",
    pfCard3Item4: "Conversion Rate Optimization (CRO)",
    pfCard3Item5: "Budget Allocation",
    pfCard3Title: "Performance & Data Analytics",
    pfCert1By: "By Meta Blueprint",
    pfCert1Id: "ID: 132997783",
    pfCert1Sub: "Meta Advertising Standards & Ad Policies",
    pfCert1Title: "Privacy & Data Protection across Meta Technologies",
    pfCert2By: "LAU ACE & KANZ AI + Ministry of HR (KSA)",
    pfCert2Id: "ID: KANZ-ATT-AE832C3BA3",
    pfCert2Sub: "Foundational AI Proficiency",
    pfCert2Title: "AI Training Hackathon",
    pfCert3By: "Dubai Universal Blueprint for Artificial Intelligence",
    pfCert3Id: "ID: 3IFAOhZysgt4",
    pfCert3Sub: "Prompt Engineering for AI Systems",
    pfCert3Title: "One Million Prompters Initiative",
    pfCertBadge1: "Under supervision of Eng. Fadi Kaddisi",
    pfCertBadge2: "Eng. Shimaa Saleh",
    pfCertBoxMeta: "<strong>Business Khana</strong> Academy – Cairo - 2019",
    pfCertBoxName: "Professional Photography Fundamentals",
    pfCertBoxTitle: "Professional Certification",
    pfCertsHeading: "Certifications & Credentials",
    pfCertsLabel: "07 — Certifications",
    pfCertsNav: "Certs",
    pfCs1Header: "Case Study 01 — Website Migration & Infrastructure Deployment",
    pfCs1Item1: "Planned and prepared the migration process.",
    pfCs1Item2: "Migrated website files and database.",
    pfCs1Item3: "Reconfigured the hosting environment.",
    pfCs1Item4: "Resolved database encoding compatibility issues.",
    pfCs1Item5: "Performed isolated testing before deployment.",
    pfCs1Item6: "Completed DNS configuration and final cutover.",
    pfCs1Item7: "Verified website functionality after migration.",
    pfCs1Objective: "Migrated a production website between hosting environments while maintaining service continuity.",
    pfCs1ResultComment: "// Successfully completed the migration and validated the website and database after deployment.",
    pfCs2Header: "Case Study 02 — WordPress Website Migration & Optimization",
    pfCs2Item1: "Migrated the WordPress website to a new hosting environment.",
    pfCs2Item2: "Configured the new hosting structure.",
    pfCs2Item3: "Migrated and validated the website database.",
    pfCs2Item4: "Upgraded database encoding to utf8mb4.",
    pfCs2Item5: "Managed domain and DNS configuration.",
    pfCs2Item6: "Performed post-migration verification.",
    pfCs2Objective: "Migrate and optimize a WordPress website while preserving its existing functionality and content.",
    pfCs2Result: "Successfully deployed the website in the new environment with validated content, database integrity, and domain configuration.",
    pfCs3Header: "Case Study 03 — Website Infrastructure & Database Deployment",
    pfCs3Item2: "Deployed the database structure and data.",
    pfCs3Item3: "Validated table integrity and imported records.",
    pfCs3Item4: "Tested the application in an isolated environment.",
    pfCs3Item5: "Performed post-deployment verification.",
    pfCs3Objective: "Deploy and validate a web application's database and supporting environment.",
    pfCs3Result: "Successfully deployed and validated the database with 29 tables and 22,843 imported records, achieving a 100% installation success rate.",
    pfCs4Header: "Case Study 04 — Self-Hosted Application Environment",
    pfCs4Item1: "Evaluated the hosting requirements.",
    pfCs4Item3: "Configured containerized application deployment.",
    pfCs4Item4: "Tested the application locally before production deployment.",
    pfCs4Item5: "Evaluated hosting limitations and deployment requirements.",
    pfCs4Item6: "Documented the deployment process and technical requirements.",
    pfCs4Objective: "Prepare and validate a self-hosted environment for a web application.",
    pfCs4Result: "Established a tested deployment environment and identified the infrastructure requirements needed for reliable application hosting.",
    pfCs5DesignDevHeading: "Design & Development",
    pfCs5DesignItem1: "Built via WordPress to reflect visual identity",
    pfCs5DesignItem2: "Responsive and seamless user experience",
    pfCs5DesignItem3: "Migrated from Hostinger to Bluehost Pro",
    pfCs5DesignItem4: "Upgraded encoding to utf8mb4",
    pfCs5DesignItem5: "Directed Nameservers on GoDaddy",
    pfCs5EmailHeading: "Email Management",
    pfCs5EmailItem1: "Strict Zero-Downtime policy",
    pfCs5EmailItem2: "Separating web hosting from email",
    pfCs5EmailItem3: "Configuring MX Records and A records",
    pfCs5EmailItem4: "Preventing bounce and Spam classification",
    pfCs5Header: "Case Study 05 — Design & Development of geomakstudies.com",
    pfDomain1Desc: "Managing paid advertising campaigns and optimizing performance across digital platforms.",
    pfDomain1En: "Media Buying",
    pfDomain1Title: "Digital Marketing & Ad Management",
    pfDomain2Desc: "Designing visual identities, user interfaces, and user experience.",
    pfDomain2En: "Graphic Design & UI/UX",
    pfDomain2Title: "Visual Design & Development",
    pfDomain3Desc: "Developing web and mobile applications using modern and advanced technologies.",
    pfDomain3En: "App & Web Development",
    pfDomain3Title: "Programming & App Development",
    pfDomain4Desc: "Capturing advertising and real estate photos and preparing field visual content.",
    pfDomain4En: "Photography",
    pfDomain4Title: "Photography",
    pfDomain5Desc: "Editing and producing visual clips and interactive content for advertisements.",
    pfDomain5En: "Video Editing & Post-Production",
    pfDomain5Title: "Video Editing & Production",
    pfDomain6Desc: "Direct communication with clients and owners and building sustainable relationships.",
    pfDomain6En: "Client & Relationship Management",
    pfDomain6Title: "Relationship & Communication Management",
    pfDomain7Desc: "Managing and following up on contracts and saving and formatting administrative files.",
    pfDomain7En: "Document & Contract Coordination",
    pfDomain7Title: "Document & Contract Coordination",
    pfDomain8Desc: "Managing real estate operations and following up on client and buyer portfolios.",
    pfDomain8En: "Real Estate Operations",
    pfDomain8Title: "Real Estate Sector & Portfolio Management",
    pfDomain9Desc: "Managing website hosting, servers, and technical infrastructure.",
    pfDomain9En: "Web Hosting & Infrastructure",
    pfDomain9Title: "Server & Infrastructure Management",
    pfDomain10Desc: "Designing and managing databases and cloud backend solutions.",
    pfDomain10En: "Databases & Cloud Backend",
    pfDomain10Title: "Databases & Engineering",
    pfDomain11Desc: "Using AI technologies and prompt engineering to improve productivity.",
    pfDomain11En: "AI & Prompt Engineering",
    pfDomain11Title: "AI & Prompt Engineering",
    pfDomain12Desc: "3D modeling and design using Blender software.",
    pfDomain12En: "3D Modeling - Blender",
    pfDomain12Title: "3D Design & Modeling",
    pfDomainsHeading: "Complete 12 Domains Overview",
    pfDomainsLabel: "11 — Domains Overview",
    pfDomainsSubtitle: "Comprehensive overview of all specialized domains where I have direct practical experience",
    pfEquip1: "Godox Lighting System",
    pfEquip2: "Speedlite Flashes",
    pfEquip3: "Octa Softbox",
    pfEquip5: "Professional Cameras",
    pfEquip6: "Full Studio Equipments",
    pfEquipmentLabel: "Equipment Used",
    pfExcelAdvanced: "Microsoft Excel (Advanced)",
    pfGenAiImagery: "Generative AI Imagery",
    pfHeroEyebrow: "Professional Profile · 2026",
    pfHeroLocation: "Abu Dhabi, UAE",
    pfHeroName: "AHMED MOHAMED <span class=\"accent\">ZAYED</span>",
    pfHighlightText: "This experience contributed to developing my visual vision, which directly reflected on the quality of my work in graphic design, UI design, and advertising content production, where I rely on composition, lighting, and color principles to create more impactful and professional marketing materials.",
    pfHighlightTitle: "Impact on Visual Vision & Creativity",
    pfJourneyP1: "I have over 7 years of experience in professional photography, where I executed and managed more than 300 diverse photo sessions including wedding photography, individual portraits, events and occasions, with a focus on delivering high-quality images that meet commercial and artistic standards.",
    pfJourneyP2: "I have practical experience in using professional cameras and lighting and studio equipment, including Godox lighting systems, Speedlite flashes, Octa Softbox, and Godox X1 Trigger wireless controllers, in addition to various lighting setups to achieve the best results in indoor and outdoor environments.",
    pfJourneyTitle: "Professional Journey",
    pfNameserversHeading: "Nameservers Transfer on GoDaddy",
    pfObjectiveLabel: "Objective:",
    pfOverviewNav: "O. V.",
    pfPhotoHeading: "Photography Experience",
    pfPhotoLabel: "10 — Photography",
    pfPhotoStat1: "Years of Professional Experience",
    pfPhotoStat2: "Photo Sessions Executed",
    pfPhotoStat3: "Certified Professional Certificate",
    pfPhotoSubtitle: "Documented professional record in artistic and commercial photography spanning years",
    pfPhotographyNav: "Photo",
    pfPortfolioAlert: "Generated and qualified direct real estate opportunities contributing to a property portfolio exceeding AED 8.1M in market value.",
    pfPreparedAppEnv: "Prepared the application environment.",
    pfPromptEng: "Prompt Engineering",
    pfRent: "Rent",
    pfRentBudget: "AED 1,580,000 / year",
    pfResultHeading: "Result",
    pfResultLabelColon: "Result:",
    pfSkillsCard1Title: "Design & Creativity",
    pfSkillsCard2Title: "CMS & Productivity",
    pfSkillsCard3Title: "Artificial Intelligence",
    pfSkillsHeading: "Technical Skills & Tools",
    pfSkillsLabel: "04 — Skills",
    pfSkillsNav: "Skills",
    pfStat1Label: "Designs/Videos Produced",
    pfStat2Label: "Impressions",
    pfStat3Label: "Direct Reach",
    pfStat4Label: "Managed Ad Budgets",
    pfSummaryHeading: "Professional Summary",
    pfSummaryLabel: "01 — Summary",
    pfSummaryNav: "Summary",
    pfSummaryText: "Multi-skilled specialist in Digital Marketing, Web Development, and UI/UX Design (Full-Stack Marketer & Web/UI/UX Developer), based in Abu Dhabi. Experienced in managing high-performance advertising campaigns across Meta and TikTok Ads, designing and developing digital platforms, with expertise in server management and content protection. Contributed to increasing sales and generating leads for real estate and retail sectors through data-driven marketing strategies, effective user experiences, and professional visual designs. I also employ AI tools and Prompt Engineering to automate and optimize workflows, and hold international certifications from Meta Blueprint and the Digital Hackathon (LAU & KANZ AI).",
    pfTable1Title: "Ad Campaign Performance (Meta Ads)",
    pfTable2Title: "Property Lead Requests (Properties Wanted)",
    pfTable3Title: "Acquired Real Estate Portfolio (Directly from Owners)",
    pfTag1: "Meta Ads Manager",
    pfTag2: "Lead Generation",
    pfTag3: "ROI Optimization",
    pfTag4: "Graphic Design",
    pfTag5: "WordPress",
    pfTag6: "UI/UX",
    pfTag7: "AI Workflows",
    pfTechHeading: "Technical Projects & Case Studies",
    pfTechLabel: "06 — Technical Work",
    pfTechSubtitle: "Selected technical projects involving website migration, deployment, infrastructure, and digital asset protection.",
    pfTechnicalNav: "Tech.",
    pfThAdSet: "Ad Set Name",
    pfThCostResult: "Cost/Result",
    pfThCtr: "CTR",
    pfThImpressions: "Impressions",
    pfThMetric: "Metric",
    pfThReach: "Reach",
    pfThReqBudget: "Requests with Budget",
    pfThResults: "Results",
    pfThSpend: "Spend",
    pfThTotalBudget: "Total Budget",
    pfThTotalRequests: "Total Requests",
    pfThTotalWeighted: "Total / Weighted Value",
    pfThTransType: "Transaction Type",
    pfToolsHeading: "Tools & Software",
    pfToolsLabel: "08 — Tools",
    pfToolsNav: "Tools",
    pfToolsSubtitle: "Integrated technical ecosystem used daily in the work environment",
    pfTotalArea: "Total Built-up / Plot Area",
    pfTotalAreaVal: "350,513 sq ft",
    pfTotalPortfolioValue: "Total Portfolio Value",
    pfTotalProperties: "Total Properties",
    pfTotalPropertiesVal: "6 Properties",
    pfTrainingAxesLabel: "Training Program Axes:",
    pfUaeBroad: "UAE (Broad)",
    pfWebDevCardDesc: "Developing and designing web platforms and APIs using Visual Studio Code and Python:",
    pfWebDevCardTitle: "Web & Systems Development",
    pfWebDevItem1: "RESTful APIs & FastAPI Architecture",
    pfWebDevItem2: "Dynamic Templating (Jinja2, HTML5, CSS3)",
    pfWebDevItem3: "Database Migrations & Alembic",
    pfWebDevItem4: "Asynchronous Data Capture (JavaScript, AJAX)",
    pfWhatIDid: "What I Did"
  },

  ar: {
    dir: "rtl",

    // التنقل
    home: "الرئيسية",
    about: "من نحن",
    focus: "مجالات التركيز",
    approach: "أسلوب العمل",
    contact: "تواصل معنا",
    portfolio: "معرض الأعمال",

    // القسم الرئيسي (لا تتم ترجمة شعار "ZAYED.ART" أبداً)
    heroSubtitle: "استوديو رقمي متعدد التخصصات",
    ctaBtn: "ابدأ مشروعك",
    scroll: "تمرير",

    // من نحن
    aboutHeading: "بناء تجارب<br>رقمية متميزة",
    aboutBody1: "زايد آرت استوديو رقمي متعدد التخصصات، متخصص في تطوير المواقع، تصميم واجهات وتجربة المستخدم (UI/UX)، تطبيقات الجوال، وحلول التسويق الرقمي.",
    aboutBody2: "نجمع بين الإبداع والخبرة التقنية لبناء منتجات رقمية تحقق نتائج حقيقية للأعمال.",
    techPill1: "WordPress · React · Python",
    techPill2: "Kotlin · Jetpack Compose",
    techPill3: "Adobe Creative Cloud",
    techPill4: "إعلانات ميتا · تحسين محركات البحث (SEO) · الأتمتة",
    domainWebNum: "الويب",
    domainWebLabel: "التطوير والمنصات",
    domainMobileNum: "الجوال",
    domainMobileLabel: "تطبيقات أندرويد",
    domainDesignNum: "التصميم",
    domainDesignLabel: "واجهات وتجربة المستخدم والهوية البصرية",
    domainGrowthNum: "النمو",
    domainGrowthLabel: "التسويق والأتمتة",
    statusLabel: "// الحالة الحالية",
    statusText: "حالياً في مرحلة التطوير",
    statusSub: "نعمل على بناء الجيل الأول من منتجاتنا وخدماتنا — الإطلاق قريباً.",

    // مجالات التركيز
    focusHeading: "ماذا نقدّم",
    webDevTitle: "تطوير المواقع",
    webDevSubtitle: "حلول ووردبريس ومواقع مخصصة",
    webDevDesc: "منصات ويب مخصصة وحلول ووردبريس مصممة هندسياً لتحقيق السرعة والثبات والأداء العالي.",
    webDevFeature1: "تطوير مواقع ووردبريس مخصصة",
    webDevFeature2: "صفحات هبوط وقنوات مبيعات",
    webDevFeature3: "واجهات تطبيقات ويب بتقنية React",
    webDevFeature4: "تحسين الأداء",

    mobileTitle: "تطبيقات الجوال",
    mobileSubtitle: "تطبيقات أندرويد بمعمارية حديثة",
    mobileDesc: "تطبيقات أندرويد أصلية مبنية باستخدام Kotlin و Jetpack Compose، مع تركيز على البنية النظيفة وتجربة استخدام سلسة.",
    mobileFeature1: "Kotlin و Jetpack Compose",
    mobileFeature2: "إدارة الحالة (State Management)",
    mobileFeature3: "تصميمات Material UI",
    mobileFeature4: "التجهيز لنشر التطبيقات",

    designTitle: "التصميم والهوية البصرية",
    designSubtitle: "تصميم الواجهات والهوية البصرية",
    designDesc: "تصاميم تركّز على المستخدم توازن بين الجمال والوظيفة، من الهويات البصرية إلى واجهات التطبيقات والمواقع السلسة.",
    designFeature1: "تصميم الهوية البصرية والشعارات",
    designFeature2: "تصميم واجهات الجوال والويب",
    designFeature3: "نماذج أولية باستخدام Figma",
    designFeature4: "أصول بصرية احترافية",

    marketingTitle: "التسويق الرقمي",
    marketingSubtitle: "التسويق الأدائي والأتمتة",
    marketingDesc: "استراتيجيات مبنية على البيانات تضع العلامات التجارية أمام الجمهور المستهدف وتُبسّط التواصل من خلال الأتمتة.",
    marketingFeature1: "إعلانات ميتا وجوجل",
    marketingFeature2: "توليد عملاء محتملين ذوي قيمة عالية",
    marketingFeature3: "أتمتة التسويق والواتساب",
    marketingFeature4: "تحسين الظهور المحلي (SEO)",

    // أسلوب العمل
    approachHeading: "كيف نعمل",
    approach1Title: "الجودة أولاً",
    approach1Desc: "كل بكسل وكل سطر برمجي مهم. نحافظ على أعلى المعايير في كل ما نُنجزه.",
    approach2Title: "سير عمل مدعوم بالذكاء الاصطناعي",
    approach2Desc: "دمج أدوات الذكاء الاصطناعي والأتمتة المتقدمة لتقديم نتائج أسرع وأذكى وأكثر كفاءة.",
    approach3Title: "مدفوع بالأداء",
    approach3Desc: "مصمم لتحقيق التحويلات وقابل للتوسّع. كل قرار مبني على بيانات ويركّز على النتائج.",

    // تواصل معنا والتذييل
    contactHeading: "لنبنِ<br>شيئاً عظيماً معاً",
    emailLabel: "البريد الإلكتروني",
    phoneLabel: "الهاتف",
    copyrightText: "© 2026 Zayed.Art. جميع الحقوق محفوظة.",

    // ==== صفحة البروفايل (portfolio.html) ====
    pf3dCardDesc: "تصميم بيئات وأصول ثلاثية الأبعاد مع الالتزام بـ:",
    pf3dCardTitle: "النمذجة ثلاثية الأبعاد",
    pf3dItem1: "مقاييس وأبعاد واقعية ودقيقة",
    pf3dItem2: "معايير إضاءة وانعكاس واقعية",
    pf3dItem3: "مخرجات فنية وتصميم بيئي متكامل",
    pfAchievementsHeading: "إنجازات التسويق واقتناء الأصول",
    pfAchievementsLabel: "02 — الإنجازات",
    pfAchievementsNav: "الإنجازات",
    pfAiWorkflows: "سير عمل بمساعدة الذكاء الاصطناعي",
    pfAndroidCardDesc: "تدريب فعلي وتطوير تطبيقات جوال باستخدام Kotlin وAndroid Studio:",
    pfAndroidCardTitle: "تطوير تطبيقات أندرويد",
    pfAndroidItem2: "إدارة الحالة",
    pfAndroidItem3: "معدّلات التخطيط (Layout Modifiers)",
    pfAppsNote: "<strong>ZaMister:</strong> منصة لإدارة حضور الطلاب مع إشعارات واتساب.<br>\n                <strong>ZaMoney:</strong> تطبيق لتتبع الميزانية الشخصية والمصروفات.",
    pfAxis1: "تركيب الكاميرات الاحترافية وآلية عملها.",
    pfAxis2: "دراسة أنواع العدسات واستخداماتها العملية.",
    pfAxis3: "التصوير الاحترافي بالوضع اليدوي (Manual Mode).",
    pfAxis4: "قواعد التكوين وتقنيات وأنواع التصوير المختلفة.",
    pfAxis5: "أساسيات الإضاءة والتحكم في التعريض الضوئي.",
    pfAxis6: "معالجة الصور وإتقان التعديل باستخدام Adobe Lightroom.",
    pfBackHome: "→ العودة للرئيسية",
    pfBuy: "شراء",
    pfCard1Item1: "إدارة إعلانات ميتا (فيسبوك/إنستغرام)",
    pfCard1Item2: "إدارة إعلانات تيك توك",
    pfCard1Item3: "إعداد الحملات واختبار A/B",
    pfCard1Item4: "استهداف الجمهور وإعادة الاستهداف",
    pfCard1Title: "إدارة الحملات المدفوعة",
    pfCard2Item1: "اكتساب عملاء محتملين ذوي نية شراء عالية",
    pfCard2Item2: "الحفاظ على قيمة المحفظة العقارية",
    pfCard2Item3: "توسيع قمع التحويل",
    pfCard2Item4: "إدارة علاقات العملاء (CRM) ومعالجة الاستفسارات",
    pfCard2Title: "توليد العملاء المحتملين ونمو المحفظة",
    pfCard3Item1: "تحسين العائد على الاستثمار والإنفاق الإعلاني (ROI/ROAS)",
    pfCard3Item2: "تتبع التحليلات",
    pfCard3Item3: "خفض تكلفة العميل المحتمل (CPL)",
    pfCard3Item4: "تحسين معدل التحويل (CRO)",
    pfCard3Item5: "توزيع الميزانية",
    pfCard3Title: "الأداء وتحليل البيانات",
    pfCert1By: "من Meta Blueprint",
    pfCert1Id: "المعرف: 132997783",
    pfCert1Sub: "معايير وسياسات إعلانات ميتا",
    pfCert1Title: "الخصوصية وحماية البيانات عبر تقنيات ميتا",
    pfCert2By: "LAU ACE و KANZ AI + وزارة الموارد البشرية (السعودية)",
    pfCert2Id: "المعرف: KANZ-ATT-AE832C3BA3",
    pfCert2Sub: "الكفاءة الأساسية في الذكاء الاصطناعي",
    pfCert2Title: "هاكاثون تدريب الذكاء الاصطناعي",
    pfCert3By: "مخطط دبي الشامل للذكاء الاصطناعي",
    pfCert3Id: "المعرف: 3IFAOhZysgt4",
    pfCert3Sub: "هندسة الأوامر لأنظمة الذكاء الاصطناعي",
    pfCert3Title: "مبادرة مليون مبرمج أوامر (One Million Prompters)",
    pfCertBadge1: "تحت إشراف المهندس فادي قديسي",
    pfCertBadge2: "المهندسة شيماء صالح",
    pfCertBoxMeta: "أكاديمية <strong>Business Khana</strong> – القاهرة - 2019",
    pfCertBoxName: "أساسيات التصوير الفوتوغرافي الاحترافي",
    pfCertBoxTitle: "الشهادة المهنية",
    pfCertsHeading: "الشهادات والاعتمادات",
    pfCertsLabel: "07 — الشهادات",
    pfCertsNav: "الشهادات",
    pfCs1Header: "دراسة حالة 01 — ترحيل الموقع ونشر البنية التحتية",
    pfCs1Item1: "التخطيط للعملية والإعداد للترحيل.",
    pfCs1Item2: "ترحيل ملفات الموقع وقاعدة البيانات.",
    pfCs1Item3: "إعادة تهيئة بيئة الاستضافة.",
    pfCs1Item4: "حل مشكلات توافق ترميز قاعدة البيانات.",
    pfCs1Item5: "إجراء اختبار معزول قبل النشر.",
    pfCs1Item6: "إتمام إعداد DNS والتحويل النهائي.",
    pfCs1Item7: "التحقق من عمل الموقع بعد الترحيل.",
    pfCs1Objective: "تم ترحيل موقع إنتاجي بين بيئتي استضافة مع الحفاظ على استمرارية الخدمة.",
    pfCs1ResultComment: "// تم إتمام الترحيل بنجاح والتحقق من الموقع وقاعدة البيانات بعد النشر.",
    pfCs2Header: "دراسة حالة 02 — ترحيل وتحسين موقع ووردبريس",
    pfCs2Item1: "ترحيل موقع ووردبريس إلى بيئة استضافة جديدة.",
    pfCs2Item2: "إعداد بنية الاستضافة الجديدة.",
    pfCs2Item3: "ترحيل والتحقق من قاعدة بيانات الموقع.",
    pfCs2Item4: "ترقية ترميز قاعدة البيانات إلى utf8mb4.",
    pfCs2Item5: "إدارة النطاق وإعداد DNS.",
    pfCs2Item6: "إجراء التحقق بعد الترحيل.",
    pfCs2Objective: "ترحيل وتحسين موقع ووردبريس مع الحفاظ على وظائفه ومحتواه الحالي.",
    pfCs2Result: "تم نشر الموقع بنجاح في البيئة الجديدة مع التحقق من المحتوى وسلامة قاعدة البيانات وإعداد النطاق.",
    pfCs3Header: "دراسة حالة 03 — نشر البنية التحتية وقاعدة البيانات للموقع",
    pfCs3Item2: "نشر بنية وبيانات قاعدة البيانات.",
    pfCs3Item3: "التحقق من سلامة الجداول والسجلات المستوردة.",
    pfCs3Item4: "اختبار التطبيق في بيئة معزولة.",
    pfCs3Item5: "إجراء التحقق بعد النشر.",
    pfCs3Objective: "نشر والتحقق من قاعدة بيانات تطبيق ويب والبيئة الداعمة له.",
    pfCs3Result: "تم نشر والتحقق من قاعدة البيانات بنجاح بواقع 29 جدولاً و22,843 سجلاً مستورداً، بمعدل نجاح تثبيت بلغ 100%.",
    pfCs4Header: "دراسة حالة 04 — بيئة تطبيق ذاتية الاستضافة",
    pfCs4Item1: "تقييم متطلبات الاستضافة.",
    pfCs4Item3: "إعداد نشر التطبيق بالحاويات (Containers).",
    pfCs4Item4: "اختبار التطبيق محلياً قبل النشر للإنتاج.",
    pfCs4Item5: "تقييم قيود الاستضافة ومتطلبات النشر.",
    pfCs4Item6: "توثيق عملية النشر والمتطلبات التقنية.",
    pfCs4Objective: "تجهيز والتحقق من بيئة استضافة ذاتية لتطبيق ويب.",
    pfCs4Result: "تم إنشاء بيئة نشر مُختبرة وتحديد متطلبات البنية التحتية اللازمة لاستضافة موثوقة للتطبيق.",
    pfCs5DesignDevHeading: "التصميم والتطوير",
    pfCs5DesignItem1: "تم بناؤه عبر ووردبريس ليعكس الهوية البصرية",
    pfCs5DesignItem2: "تجربة مستخدم متجاوبة وسلسة",
    pfCs5DesignItem3: "تم الترحيل من Hostinger إلى Bluehost Pro",
    pfCs5DesignItem4: "ترقية الترميز إلى utf8mb4",
    pfCs5DesignItem5: "توجيه خوادم الأسماء (Nameservers) على GoDaddy",
    pfCs5EmailHeading: "إدارة البريد الإلكتروني",
    pfCs5EmailItem1: "سياسة صارمة لانعدام التوقف (Zero-Downtime)",
    pfCs5EmailItem2: "فصل استضافة الموقع عن البريد الإلكتروني",
    pfCs5EmailItem3: "إعداد سجلات MX وA",
    pfCs5EmailItem4: "منع الارتداد والتصنيف كرسائل مزعجة (Spam)",
    pfCs5Header: "دراسة حالة 05 — تصميم وتطوير موقع geomakstudies.com",
    pfDomain1Desc: "إدارة الحملات الإعلانية المدفوعة وتحسين الأداء عبر المنصات الرقمية.",
    pfDomain1En: "شراء الإعلام",
    pfDomain1Title: "التسويق الرقمي وإدارة الإعلانات",
    pfDomain2Desc: "تصميم الهويات البصرية وواجهات وتجارب المستخدم.",
    pfDomain2En: "التصميم الجرافيكي وتجربة المستخدم",
    pfDomain2Title: "التصميم البصري والتطوير",
    pfDomain3Desc: "تطوير تطبيقات الويب والجوال باستخدام تقنيات حديثة ومتقدمة.",
    pfDomain3En: "تطوير التطبيقات والمواقع",
    pfDomain3Title: "البرمجة وتطوير التطبيقات",
    pfDomain4Desc: "التقاط صور إعلانية وعقارية وإعداد محتوى بصري ميداني.",
    pfDomain4En: "التصوير الفوتوغرافي",
    pfDomain4Title: "التصوير الفوتوغرافي",
    pfDomain5Desc: "مونتاج وإنتاج مقاطع مرئية ومحتوى تفاعلي للإعلانات.",
    pfDomain5En: "مونتاج الفيديو والإنتاج اللاحق",
    pfDomain5Title: "مونتاج وإنتاج الفيديو",
    pfDomain6Desc: "التواصل المباشر مع العملاء والملاك وبناء علاقات مستدامة.",
    pfDomain6En: "إدارة العملاء والعلاقات",
    pfDomain6Title: "إدارة العلاقات والتواصل",
    pfDomain7Desc: "إدارة ومتابعة العقود وحفظ وتنسيق الملفات الإدارية.",
    pfDomain7En: "تنسيق الوثائق والعقود",
    pfDomain7Title: "تنسيق الوثائق والعقود",
    pfDomain8Desc: "إدارة العمليات العقارية ومتابعة محافظ العملاء والمشترين.",
    pfDomain8En: "العمليات العقارية",
    pfDomain8Title: "القطاع العقاري وإدارة المحافظ",
    pfDomain9Desc: "إدارة استضافة المواقع والخوادم والبنية التحتية التقنية.",
    pfDomain9En: "استضافة المواقع والبنية التحتية",
    pfDomain9Title: "إدارة الخوادم والبنية التحتية",
    pfDomain10Desc: "تصميم وإدارة قواعد البيانات وحلول الأنظمة الخلفية السحابية.",
    pfDomain10En: "قواعد البيانات والأنظمة السحابية",
    pfDomain10Title: "قواعد البيانات والهندسة",
    pfDomain11Desc: "استخدام تقنيات الذكاء الاصطناعي وهندسة الأوامر لتحسين الإنتاجية.",
    pfDomain11En: "الذكاء الاصطناعي وهندسة الأوامر",
    pfDomain11Title: "الذكاء الاصطناعي وهندسة الأوامر",
    pfDomain12Desc: "النمذجة والتصميم ثلاثي الأبعاد باستخدام برنامج Blender.",
    pfDomain12En: "النمذجة ثلاثية الأبعاد - Blender",
    pfDomain12Title: "التصميم والنمذجة ثلاثية الأبعاد",
    pfDomainsHeading: "نظرة عامة شاملة على المجالات الـ12",
    pfDomainsLabel: "11 — نظرة عامة على المجالات",
    pfDomainsSubtitle: "نظرة شاملة على جميع المجالات المتخصصة التي أمتلك فيها خبرة عملية مباشرة",
    pfEquip1: "نظام إضاءة Godox",
    pfEquip2: "فلاشات Speedlite",
    pfEquip3: "سوفت بوكس أوكتا (Octa Softbox)",
    pfEquip5: "كاميرات احترافية",
    pfEquip6: "معدات استوديو كاملة",
    pfEquipmentLabel: "المعدات المستخدمة",
    pfExcelAdvanced: "Microsoft Excel (متقدم)",
    pfGenAiImagery: "الصور التوليدية بالذكاء الاصطناعي",
    pfHeroEyebrow: "الملف المهني · 2026",
    pfHeroLocation: "أبوظبي، الإمارات العربية المتحدة",
    pfHeroName: "أحمد محمد <span class=\"accent\">زايد</span>",
    pfHighlightText: "ساهمت هذه الخبرة في تطوير رؤيتي البصرية، وانعكس ذلك مباشرة على جودة عملي في التصميم الجرافيكي وتصميم واجهات المستخدم وإنتاج المحتوى الإعلاني، حيث أعتمد على مبادئ التكوين والإضاءة والألوان لإنشاء مواد تسويقية أكثر تأثيراً واحترافية.",
    pfHighlightTitle: "الأثر على الرؤية البصرية والإبداع",
    pfJourneyP1: "أمتلك أكثر من 7 سنوات من الخبرة في التصوير الاحترافي، حيث نفّذت وأدرت أكثر من 300 جلسة تصوير متنوعة شملت تصوير الأعراس، البورتريه الفردي، المناسبات والفعاليات، مع التركيز على تقديم صور عالية الجودة تلبي المعايير التجارية والفنية.",
    pfJourneyP2: "لدي خبرة عملية في استخدام الكاميرات الاحترافية ومعدات الإضاءة والاستوديو، بما في ذلك أنظمة إضاءة Godox، فلاشات Speedlite، سوفت بوكس أوكتا (Octa Softbox)، وأجهزة تحكم لاسلكية Godox X1 Trigger، بالإضافة إلى إعدادات إضاءة متنوعة لتحقيق أفضل النتائج في البيئات الداخلية والخارجية.",
    pfJourneyTitle: "المسيرة المهنية",
    pfNameserversHeading: "نقل خوادم الأسماء (Nameservers) على GoDaddy",
    pfObjectiveLabel: "الهدف:",
    pfOverviewNav: "نظرة عامة",
    pfPhotoHeading: "خبرة التصوير الفوتوغرافي",
    pfPhotoLabel: "10 — التصوير",
    pfPhotoStat1: "سنوات من الخبرة المهنية",
    pfPhotoStat2: "جلسة تصوير تم تنفيذها",
    pfPhotoStat3: "شهادة احترافية معتمدة",
    pfPhotoSubtitle: "سجل مهني موثق في التصوير الفني والتجاري عبر سنوات",
    pfPhotographyNav: "التصوير",
    pfPortfolioAlert: "تم توليد وتأهيل فرص عقارية مباشرة ساهمت في محفظة عقارية تتجاوز قيمتها السوقية 8.1 مليون درهم إماراتي.",
    pfPreparedAppEnv: "تجهيز بيئة التطبيق.",
    pfPromptEng: "هندسة الأوامر (Prompt Engineering)",
    pfRent: "إيجار",
    pfRentBudget: "AED 1,580,000 / سنوياً",
    pfResultHeading: "النتيجة",
    pfResultLabelColon: "النتيجة:",
    pfSkillsCard1Title: "التصميم والإبداع",
    pfSkillsCard2Title: "أنظمة إدارة المحتوى والإنتاجية",
    pfSkillsCard3Title: "الذكاء الاصطناعي",
    pfSkillsHeading: "المهارات والأدوات التقنية",
    pfSkillsLabel: "04 — المهارات",
    pfSkillsNav: "المهارات",
    pfStat1Label: "تصميم/فيديو تم إنتاجه",
    pfStat2Label: "مرات الظهور (Impressions)",
    pfStat3Label: "وصول مباشر",
    pfStat4Label: "ميزانيات إعلانية تمت إدارتها",
    pfSummaryHeading: "الملخص المهني",
    pfSummaryLabel: "01 — الملخص",
    pfSummaryNav: "الملخص",
    pfSummaryText: "متخصص متعدد المهارات في التسويق الرقمي وتطوير الويب وتصميم واجهات وتجربة المستخدم (مسوّق ومطوّر ويب/UI/UX متكامل)، مقيم في أبوظبي. لدي خبرة في إدارة حملات إعلانية عالية الأداء عبر إعلانات ميتا وتيك توك، وتصميم وتطوير المنصات الرقمية، مع خبرة في إدارة الخوادم وحماية المحتوى. ساهمت في زيادة المبيعات وتوليد العملاء المحتملين لقطاعي العقارات والتجزئة من خلال استراتيجيات تسويقية مبنية على البيانات، وتجارب مستخدم فعّالة، وتصاميم بصرية احترافية. كما أستخدم أدوات الذكاء الاصطناعي وهندسة الأوامر لأتمتة وتحسين سير العمل، وأحمل شهادات دولية من Meta Blueprint وهاكاثون Digital Hackathon (LAU & KANZ AI).",
    pfTable1Title: "أداء الحملة الإعلانية (إعلانات ميتا)",
    pfTable2Title: "طلبات العملاء المحتملين للعقارات (عقارات مطلوبة)",
    pfTable3Title: "المحفظة العقارية المكتسبة (مباشرة من الملاك)",
    pfTag1: "إدارة إعلانات ميتا",
    pfTag2: "توليد العملاء المحتملين",
    pfTag3: "تحسين العائد على الاستثمار (ROI)",
    pfTag4: "التصميم الجرافيكي",
    pfTag5: "WordPress",
    pfTag6: "تصميم UI/UX",
    pfTag7: "سير عمل الذكاء الاصطناعي",
    pfTechHeading: "المشاريع التقنية ودراسات الحالة",
    pfTechLabel: "06 — الأعمال التقنية",
    pfTechSubtitle: "مشاريع تقنية مختارة تشمل ترحيل المواقع، النشر، البنية التحتية، وحماية الأصول الرقمية.",
    pfTechnicalNav: "التقنية",
    pfThAdSet: "مجموعة الإعلانات",
    pfThCostResult: "التكلفة لكل نتيجة",
    pfThCtr: "معدل النقر (CTR)",
    pfThImpressions: "مرات الظهور",
    pfThMetric: "المؤشر",
    pfThReach: "الوصول",
    pfThReqBudget: "طلبات محددة الميزانية",
    pfThResults: "النتائج",
    pfThSpend: "الإنفاق",
    pfThTotalBudget: "إجمالي الميزانية",
    pfThTotalRequests: "إجمالي الطلبات",
    pfThTotalWeighted: "الإجمالي / القيمة الموزونة",
    pfThTransType: "نوع المعاملة",
    pfToolsHeading: "الأدوات والبرمجيات",
    pfToolsLabel: "08 — الأدوات",
    pfToolsNav: "الأدوات",
    pfToolsSubtitle: "منظومة تقنية متكاملة تُستخدم يومياً في بيئة العمل",
    pfTotalArea: "إجمالي المساحة المبنية / مساحة الأرض",
    pfTotalAreaVal: "350,513 قدم مربع",
    pfTotalPortfolioValue: "إجمالي قيمة المحفظة",
    pfTotalProperties: "إجمالي العقارات",
    pfTotalPropertiesVal: "6 عقارات",
    pfTrainingAxesLabel: "محاور البرنامج التدريبي:",
    pfUaeBroad: "الإمارات (واسع)",
    pfWebDevCardDesc: "تطوير وتصميم منصات الويب وواجهات البرمجة (APIs) باستخدام Visual Studio Code وبايثون:",
    pfWebDevCardTitle: "تطوير الويب والأنظمة",
    pfWebDevItem1: "واجهات RESTful وبنية FastAPI",
    pfWebDevItem2: "القوالب الديناميكية (Jinja2, HTML5, CSS3)",
    pfWebDevItem3: "ترحيل قواعد البيانات وAlembic",
    pfWebDevItem4: "التقاط البيانات غير المتزامن (JavaScript, AJAX)",
    pfWhatIDid: "ما قمت به"
  }
};

// 1. اكتشاف لغة جهاز المستخدم تلقائياً
function getPreferredLanguage() {
  // التحقق أولاً إذا كان المستخدم اختار لغة من قبل وتخزينها
  const savedLang = localStorage.getItem("user_lang");
  if (savedLang) return savedLang;

  // معرفة لغة جهاز/متصفح الزائر (مثال: 'ar-EG' أو 'en-US')
  const browserLang = window.navigator.language || window.navigator.userLanguage;

  // إذا كانت اللغة تبدأ بـ ar نختار العربية، غير ذلك الإنجليزية
  return browserLang.startsWith("ar") ? "ar" : "en";
}

// 2. تطبيق اللغة على العناصر والاتجاه (RTL / LTR)
function setLanguage(lang) {
  const currentData = translations[lang] || translations.en;

  // تغيير الاتجاه ولغة الصفحة HTML
  document.documentElement.lang = lang;
  document.documentElement.dir = currentData.dir;

  // حفظ تفضيل المستخدم
  localStorage.setItem("user_lang", lang);

  // تحديث كافة العناصر المسندة بـ data-i18n
  document.querySelectorAll("[data-i18n]").forEach(element => {
    const key = element.getAttribute("data-i18n");
    if (currentData[key]) {
      element.innerHTML = currentData[key];
    }
  });
}

// تشغيل الكشف التلقائي عند تحميل الصفحة
document.addEventListener("DOMContentLoaded", () => {
  const initialLang = getPreferredLanguage();
  setLanguage(initialLang);
});