/*
 * AUTO-GENERATED FILE
 * Do not edit manually.
 * Generated by GitHub Actions.
 */

const photography = {
  "alexandria": [
    "/assets/photography/alexandria/IMG_3743%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3744%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3749%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3751%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3761%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3762%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3765%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3766%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3771%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3773%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3776%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3781%20copy%202.webp",
    "/assets/photography/alexandria/IMG_3782%20copy%202.webp",
    "/assets/photography/alexandria/_MG_4299%20copy%202.webp",
    "/assets/photography/alexandria/_MG_4303%20copy%202.webp"
  ]
,
  "cairo": [
    "/assets/photography/cairo/DSCN7285%20copy%202.webp",
    "/assets/photography/cairo/IMG_0006%20copy%202.webp",
    "/assets/photography/cairo/IMG_0052%20copy%202.webp",
    "/assets/photography/cairo/IMG_0058%20copy.webp",
    "/assets/photography/cairo/IMG_0074%20copy%202.webp",
    "/assets/photography/cairo/IMG_0076.webp",
    "/assets/photography/cairo/IMG_0090%20copy.webp",
    "/assets/photography/cairo/IMG_0119%20copy%202.webp"
  ]
,
  "matrouh": [
    "/assets/photography/matrouh/DSCN6953%20copy.webp",
    "/assets/photography/matrouh/DSCN6974%20copy.webp",
    "/assets/photography/matrouh/DSCN6981%20copy.webp",
    "/assets/photography/matrouh/DSCN6991%20copy.webp",
    "/assets/photography/matrouh/DSCN7000%20copy.webp",
    "/assets/photography/matrouh/DSCN7003%20copy.webp",
    "/assets/photography/matrouh/IMG_0049%20copy.webp",
    "/assets/photography/matrouh/IMG_0297%20copy%202.webp",
    "/assets/photography/matrouh/IMG_1036%20copy%202.webp",
    "/assets/photography/matrouh/IMG_1045%20copy%202.webp",
    "/assets/photography/matrouh/IMG_2365%20copy.webp",
    "/assets/photography/matrouh/IMG_2379%20copy.webp",
    "/assets/photography/matrouh/IMG_2384%20copy.webp",
    "/assets/photography/matrouh/IMG_4214-2%20copy%202.webp",
    "/assets/photography/matrouh/IMG_4316%20copy%202.webp",
    "/assets/photography/matrouh/IMG_4403%20copy.webp",
    "/assets/photography/matrouh/IMG_5798%20copy.webp",
    "/assets/photography/matrouh/IMG_5945%20copy%202.webp",
    "/assets/photography/matrouh/IMG_6766%20copy.webp",
    "/assets/photography/matrouh/_MG_6872%20copy.webp"
  ]
,
  "uae": [
    "/assets/photography/uae/IMG_7480%20copy%203.webp",
    "/assets/photography/uae/IMG_7486%20copy%202.webp",
    "/assets/photography/uae/IMG_7489%20copy%202.webp",
    "/assets/photography/uae/IMG_7491%20copy%202.webp",
    "/assets/photography/uae/IMG_7507%20copy%202.webp",
    "/assets/photography/uae/IMG_7513%20copy.webp",
    "/assets/photography/uae/IMG_7516%20copy.webp",
    "/assets/photography/uae/IMG_7538%20copy%202.webp",
    "/assets/photography/uae/IMG_7549%20copy.webp",
    "/assets/photography/uae/IMG_7555%20copy.webp",
    "/assets/photography/uae/IMG_7568%20copy.webp",
    "/assets/photography/uae/IMG_7572%20copy%202.webp",
    "/assets/photography/uae/IMG_7581%20copy.webp",
    "/assets/photography/uae/IMG_7586%20copy.webp",
    "/assets/photography/uae/IMG_7597%20copy.webp"
  ]
};
